import { useState, useEffect } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Users, BookOpen, Clock, BookCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

const AdminDashboard = () => {
  const [user, setUser] = useState<any>(null);
  const [organization, setOrganization] = useState<any>(null);
  const [courseRequests, setCourseRequests] = useState<any[]>([]);
  const [orgName, setOrgName] = useState("");
  const [showCreateOrg, setShowCreateOrg] = useState(false);
  const [stats, setStats] = useState({
    totalUsers: 0,
    activeCourses: 0,
    pendingCourses: 0
  });
  const [isLoading, setIsLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    const fetchData = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      setUser(user);

      // Check if admin has an organization
      const { data: profile } = await supabase
        .from('profiles')
        .select('organization_id')
        .eq('id', user.id)
        .single();

      if (profile?.organization_id) {
        const { data: orgData } = await supabase
          .from('organizations')
          .select('*')
          .eq('id', profile.organization_id)
          .single();
        
        setOrganization(orgData);
        
        // Fetch pending course requests within organization
        const { data: coursesData } = await supabase
          .from('courses')
          .select('*, profiles(full_name, email)')
          .eq('organization_id', profile.organization_id)
          .eq('status', 'pending');

        setCourseRequests(coursesData || []);

        // Fetch organization-scoped stats
        const { count: userCount } = await supabase
          .from('profiles')
          .select('*', { count: 'exact', head: true })
          .eq('organization_id', profile.organization_id);

        const { count: courseCount } = await supabase
          .from('courses')
          .select('*', { count: 'exact', head: true })
          .eq('organization_id', profile.organization_id)
          .eq('status', 'approved');

        const { count: pendingCourseCount } = await supabase
          .from('courses')
          .select('*', { count: 'exact', head: true })
          .eq('organization_id', profile.organization_id)
          .eq('status', 'pending');

        setStats({
          totalUsers: userCount || 0,
          activeCourses: courseCount || 0,
          pendingCourses: pendingCourseCount || 0
        });
      } else {
        setShowCreateOrg(true);
      }

      setIsLoading(false);
    };

    fetchData();
  }, []);

  const handleCreateOrganization = async () => {
    if (!orgName.trim()) {
      toast({
        title: "Error",
        description: "Please enter an organization name",
        variant: "destructive",
      });
      return;
    }

    const { data, error: orgError } = await supabase
      .from('organizations')
      .insert([{
        name: orgName,
        created_by: user?.id,
        code: '' // Will be auto-generated by trigger
      }])
      .select()
      .single();

    if (orgError || !data) {
      toast({
        title: "Error",
        description: "Failed to create organization",
        variant: "destructive",
      });
      return;
    }

    // Update admin profile with organization_id
    const { error: profileError } = await supabase
      .from('profiles')
      .update({ organization_id: data.id })
      .eq('id', user?.id);

    if (profileError) {
      toast({
        title: "Error",
        description: "Failed to link organization",
        variant: "destructive",
      });
      return;
    }

    setOrganization(data);
    setShowCreateOrg(false);
    toast({
      title: "Success",
      description: `Organization created with code: ${data.code}`,
    });

    // Reload page to fetch organization data
    window.location.reload();
  };

  const handleCourseApproval = async (courseId: string, status: 'approved' | 'rejected') => {
    const { error } = await supabase
      .from('courses')
      .update({
        status,
        approved_by: user?.id,
        approved_at: status === 'approved' ? new Date().toISOString() : null
      })
      .eq('id', courseId);

    if (error) {
      toast({
        title: "Error",
        description: "Failed to update course request",
        variant: "destructive",
      });
      return;
    }

    toast({
      title: "Success",
      description: `Course request ${status}`,
    });

    // Refresh course requests
    setCourseRequests(prev => prev.filter(req => req.id !== courseId));
    setStats(prev => ({
      ...prev,
      pendingCourses: prev.pendingCourses - 1,
      activeCourses: status === 'approved' ? prev.activeCourses + 1 : prev.activeCourses
    }));
  };

  if (isLoading) {
    return (
      <DashboardLayout role="admin" userName="Loading...">
        <div>Loading...</div>
      </DashboardLayout>
    );
  }

  if (showCreateOrg && !organization) {
    return (
      <DashboardLayout role="admin" userName={user?.user_metadata?.full_name || user?.email || "Admin"}>
        <div className="max-w-2xl mx-auto mt-12">
          <Card>
            <CardHeader>
              <CardTitle>Create Your Organization</CardTitle>
              <CardDescription>
                Set up your school or institution to get started
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="orgName">Organization Name</Label>
                <Input
                  id="orgName"
                  placeholder="e.g., Springfield High School"
                  value={orgName}
                  onChange={(e) => setOrgName(e.target.value)}
                />
              </div>
              <Button onClick={handleCreateOrganization} className="w-full">
                Create Organization
              </Button>
            </CardContent>
          </Card>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout role="admin" userName={user?.user_metadata?.full_name || user?.email || "Admin"}>
      <div className="space-y-6">
        {/* Organization Info */}
        {organization && (
          <Card className="bg-gradient-primary/10 border-primary/20">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-2xl font-bold">{organization.name}</h2>
                  <p className="text-muted-foreground">Organization Code</p>
                </div>
                <div className="text-right">
                  <div className="text-3xl font-mono font-bold text-primary">
                    {organization.code}
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">
                    Share this code with teachers and students
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Quick Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Total Users</p>
                  <p className="text-2xl font-bold">{stats.totalUsers}</p>
                </div>
                <Users className="w-8 h-8 text-primary" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Active Courses</p>
                  <p className="text-2xl font-bold">{stats.activeCourses}</p>
                </div>
                <BookOpen className="w-8 h-8 text-primary" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Pending Courses</p>
                  <p className="text-2xl font-bold">{stats.pendingCourses}</p>
                </div>
                <Clock className="w-8 h-8 text-warning" />
              </div>
            </CardContent>
          </Card>
        </div>

        <Tabs defaultValue="courses" className="space-y-6">
          <TabsList>
            <TabsTrigger value="courses">Course Requests</TabsTrigger>
          </TabsList>

          <TabsContent value="courses" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <BookCheck className="w-5 h-5" />
                  Course Approval Requests
                </CardTitle>
                <CardDescription>Review and approve course creation requests</CardDescription>
              </CardHeader>
              <CardContent>
                {courseRequests.length === 0 ? (
                  <p className="text-center text-muted-foreground py-8">
                    No pending course requests
                  </p>
                ) : (
                  <div className="space-y-4">
                    {courseRequests.map((course) => (
                      <div key={course.id} className="border rounded-lg p-4">
                        <div className="flex items-start justify-between">
                          <div className="space-y-2">
                            <div>
                              <h4 className="font-semibold">{course.title}</h4>
                              <p className="text-sm text-muted-foreground">
                                by {course.profiles.full_name} ({course.profiles.email})
                              </p>
                            </div>
                            <p className="text-sm">{course.description}</p>
                            <div className="flex items-center gap-4 text-sm text-muted-foreground">
                              <span>Code: {course.course_code}</span>
                              <span>Subject: {course.subject}</span>
                              {course.grade_level && <span>Grade: {course.grade_level}</span>}
                              <span>Max Students: {course.max_students}</span>
                            </div>
                            <p className="text-xs text-muted-foreground">
                              Requested: {new Date(course.created_at).toLocaleDateString()}
                            </p>
                          </div>
                          <div className="flex gap-2">
                            <Button
                              size="sm"
                              onClick={() => handleCourseApproval(course.id, 'approved')}
                            >
                              Approve
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => handleCourseApproval(course.id, 'rejected')}
                            >
                              Reject
                            </Button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
};

export default AdminDashboard;